#!/usr/bin/env bash

digitalocean() {
	parameters=(${@:1:$(($#-($#-2)))})

	case ${#parameters[@]} in
		0 ) userSet=false;
				serverSet=false;
				;;

		1 ) userSet=true;
				serverSet=false;
				;;

		2 ) userSet=true;
				serverSet=true;
				;;
	esac

	echo $userSet $serverSet

	if $userSet; then
		user=${parameters[0]}
	else
		user="root"
	fi

	if $serverSet; then
		case ${parameters[1]} in
			"website" ) server="123.456.78.910";;

			"git" ) server="109.87.654.321";;

			* ) echo "I've never heard of ${parameters[1]}.";;
		esac
	else
		server="123.456.78.910"
	fi

	echo "ssh ${user}@${server}"
}

digitalocean "$@"
